modLoader="javafml"
loaderVersion="[0,)"
issueTrackerURL="https://github.com/matthe815/mmo-parties"
license="mit"

[[mods]]
modId="mmoparties"
version="3.0.0"
displayName="MMOParties"
#updateJSONURL=""
displayURL="https://github.com/matthe815/mmo-parties"
#logoFile="logo.png"
authors="Matthe815"
description="Adds an MMO party HUD and party system"